### ISSUE TITLE
Build for different Spark versions

### ISSUE THREAD

**Issue by kolia1985** [StabRise/spark-pdf#3]

**Comment by vicsotber** [comment]
Hello,

I'm getting the error "User class threw exception: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/datasources/FileStatusWithMetadata".

My version of Spark is 3.3.2, could I have a build for this version?

Thank you.

**Comment by kolia1985** [comment]
Hello @vicsotber 

What is version of spark-pdf you use?

Please try to use spark-pdf_2.12:0.1.7 - It is used FileStatus instead FileStatusMetadata

But for good support need to build spark-pdf for the Spark is 3.3.2.

**Comment by vicsotber** [comment]
Hello @kolia1985 

I was using spark-pdf_2.12:0.1.10.
I'll try spark-pdf_2.12:0.1.7 and let you know.

Thank you

**Comment by vicsotber** [comment]
Hello

With version spark-pdf_2.12:0.1.7 I get error "User class threw exception: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/spark/paths/SparkPath$"

**Comment by kolia1985** [comment]
@vicsotber Looks like need to build for the 3.3.2
I will try to configure building

**Comment by kolia1985** [comment]
@vicsotber I made a custom build for spark 3.3.2

com.stabrise:spark-pdf-spark33_2.12:0.1.10

https://central.sonatype.com/artifact/com.stabrise/spark-pdf-spark33_2.12

Please check notebook: https://colab.research.google.com/drive/1mHkl1kYordjrEfTkZ0Hw3sGU6HoV43Y3?usp=sharing

**Comment by vicsotber** [comment]
Hello @kolia1985 

Thank you. I will try this new version too.

**Comment by kolia1985** [comment]
Added cross building for Spark 3.3.x, 3.4.x, 3.5.x
